export const queryKeys = {
  transactions: ['transactions'] as const,
  transactionsForWallet: (walletId: number | null) => ['transactions', { walletId }] as const,
  dashboardTransactions: (walletId: number | null) => ['transactions', { walletId, limit: 10_000, offset: 0 }] as const,
  wallets: ['wallets'] as const,
  walletMembers: (walletId: number | null) => ['wallets', walletId, 'members'] as const,
  recurring: ['recurring'] as const,
  upcomingRecurring: (days = 365) => ['recurring', 'upcoming', { days }] as const,
  merchantAliases: ['merchant-aliases'] as const,
  userProfile: ['user-profile'] as const,
  monthlyReportPreferences: ['monthly-report-preferences'] as const,
  investments: ['investments'] as const,
  investmentSummary: ['investments', 'summary'] as const,
  aiAdvisorSessions: ['ai-advisor', 'sessions'] as const,
  aiAdvisorMessages: (sessionId = 'default') => ['ai-advisor', 'messages', { sessionId }] as const,
};
