import type { PersonalizationTheme, ThemeVariables } from './personalization.types';

const baseTheme: ThemeVariables = {
  '--background': '#FAFBFC',
  '--foreground': '#1F2937',
  '--card': '#FFFFFF',
  '--card-foreground': '#1F2937',
  '--popover': '#FFFFFF',
  '--popover-foreground': '#1F2937',
  '--primary': '#4F9CF9',
  '--primary-foreground': '#FFFFFF',
  '--secondary': '#EEF6FF',
  '--secondary-foreground': '#1F2937',
  '--muted': '#EEF6FF',
  '--muted-foreground': '#6B7280',
  '--accent': '#EEF6FF',
  '--accent-foreground': '#1F2937',
  '--destructive': '#FF6B6B',
  '--border': '#E5E7EB',
  '--input': '#E5E7EB',
  '--ring': '#4F9CF9',
  '--chart-1': '#4F9CF9',
  '--chart-2': '#34C759',
  '--chart-3': '#FFB84D',
  '--chart-4': '#FF6B6B',
  '--chart-5': '#6B7280',
  '--sidebar': '#FFFFFF',
  '--sidebar-foreground': '#1F2937',
  '--sidebar-primary': '#4F9CF9',
  '--sidebar-primary-foreground': '#FFFFFF',
  '--sidebar-accent': '#EEF6FF',
  '--sidebar-accent-foreground': '#1F2937',
  '--sidebar-border': '#E5E7EB',
  '--sidebar-ring': '#4F9CF9',
  '--color-primary-soft': '#EEF6FF',
  '--color-success': '#34C759',
  '--color-success-soft': '#EAFBF0',
  '--color-expense': '#FF6B6B',
  '--color-expense-soft': '#FFF1F1',
  '--color-warning': '#FFB84D',
  '--color-warning-soft': '#FFF7E8',
  '--kt-app-bg': 'oklch(0.985 0.012 232)',
  '--kt-app-surface': 'color-mix(in oklab, white 88%, transparent)',
  '--kt-app-border': 'color-mix(in oklab, oklch(0.89 0.025 232) 78%, transparent)',
  '--kt-app-shadow': '0 18px 55px rgba(15, 23, 42, 0.08)',
};

const theme = (
  details: Omit<PersonalizationTheme, 'variables'>,
  variables: Partial<ThemeVariables>
): PersonalizationTheme => ({
  ...details,
  variables: { ...baseTheme, ...variables },
});

export const DEFAULT_PERSONALIZATION_THEME_ID = 'finovo';

export const personalizationThemes: PersonalizationTheme[] = [
  theme({
    id: 'finovo',
    name: 'Finovo Blue',
    description: 'The current clean finance workspace palette.',
    swatches: ['#4F9CF9', '#34C759', '#FFB84D'],
  }, {}),
  theme({
    id: 'emerald',
    name: 'Emerald Ledger',
    description: 'Fresh green accents for savings-first workflows.',
    swatches: ['#10B981', '#0EA5E9', '#F59E0B'],
  }, {
    '--primary': '#10B981',
    '--ring': '#10B981',
    '--secondary': '#ECFDF5',
    '--muted': '#ECFDF5',
    '--accent': '#ECFDF5',
    '--chart-1': '#10B981',
    '--chart-2': '#0EA5E9',
    '--sidebar-primary': '#10B981',
    '--sidebar-accent': '#ECFDF5',
    '--sidebar-ring': '#10B981',
    '--color-primary-soft': '#ECFDF5',
  }),
  theme({
    id: 'sunrise',
    name: 'Sunrise Gold',
    description: 'Warm gold highlights with calm neutral surfaces.',
    swatches: ['#F59E0B', '#14B8A6', '#EF4444'],
  }, {
    '--primary': '#F59E0B',
    '--ring': '#F59E0B',
    '--secondary': '#FFF7ED',
    '--muted': '#FFF7ED',
    '--accent': '#FFF7ED',
    '--chart-1': '#F59E0B',
    '--chart-2': '#14B8A6',
    '--sidebar-primary': '#F59E0B',
    '--sidebar-accent': '#FFF7ED',
    '--sidebar-ring': '#F59E0B',
    '--color-primary-soft': '#FFF7ED',
  }),
  theme({
    id: 'rose',
    name: 'Rose Quartz',
    description: 'Soft rose controls for a warmer dashboard.',
    swatches: ['#F43F5E', '#8B5CF6', '#22C55E'],
  }, {
    '--primary': '#F43F5E',
    '--ring': '#F43F5E',
    '--secondary': '#FFF1F2',
    '--muted': '#FFF1F2',
    '--accent': '#FFF1F2',
    '--chart-1': '#F43F5E',
    '--chart-2': '#8B5CF6',
    '--sidebar-primary': '#F43F5E',
    '--sidebar-accent': '#FFF1F2',
    '--sidebar-ring': '#F43F5E',
    '--color-primary-soft': '#FFF1F2',
  }),
  theme({
    id: 'indigo',
    name: 'Indigo Focus',
    description: 'Deep blue-violet accents for dense analysis.',
    swatches: ['#6366F1', '#06B6D4', '#F97316'],
  }, {
    '--primary': '#6366F1',
    '--ring': '#6366F1',
    '--secondary': '#EEF2FF',
    '--muted': '#EEF2FF',
    '--accent': '#EEF2FF',
    '--chart-1': '#6366F1',
    '--chart-2': '#06B6D4',
    '--sidebar-primary': '#6366F1',
    '--sidebar-accent': '#EEF2FF',
    '--sidebar-ring': '#6366F1',
    '--color-primary-soft': '#EEF2FF',
  }),
  theme({
    id: 'aqua',
    name: 'Aqua Mint',
    description: 'Cool cyan and mint for a crisp interface.',
    swatches: ['#0891B2', '#22C55E', '#F59E0B'],
  }, {
    '--primary': '#0891B2',
    '--ring': '#0891B2',
    '--secondary': '#ECFEFF',
    '--muted': '#ECFEFF',
    '--accent': '#ECFEFF',
    '--chart-1': '#0891B2',
    '--chart-2': '#22C55E',
    '--sidebar-primary': '#0891B2',
    '--sidebar-accent': '#ECFEFF',
    '--sidebar-ring': '#0891B2',
    '--color-primary-soft': '#ECFEFF',
  }),
  theme({
    id: 'graphite',
    name: 'Graphite',
    description: 'High-contrast neutral chrome with blue actions.',
    swatches: ['#334155', '#38BDF8', '#22C55E'],
  }, {
    '--background': '#F8FAFC',
    '--foreground': '#0F172A',
    '--card-foreground': '#0F172A',
    '--primary': '#334155',
    '--ring': '#334155',
    '--secondary': '#F1F5F9',
    '--muted': '#F1F5F9',
    '--accent': '#F1F5F9',
    '--muted-foreground': '#64748B',
    '--chart-1': '#334155',
    '--chart-2': '#38BDF8',
    '--sidebar-primary': '#334155',
    '--sidebar-accent': '#F1F5F9',
    '--sidebar-ring': '#334155',
    '--color-primary-soft': '#F1F5F9',
  }),
  theme({
    id: 'orchid',
    name: 'Orchid',
    description: 'Purple accents balanced with bright success tones.',
    swatches: ['#A855F7', '#10B981', '#F97316'],
  }, {
    '--primary': '#A855F7',
    '--ring': '#A855F7',
    '--secondary': '#FAF5FF',
    '--muted': '#FAF5FF',
    '--accent': '#FAF5FF',
    '--chart-1': '#A855F7',
    '--chart-2': '#10B981',
    '--sidebar-primary': '#A855F7',
    '--sidebar-accent': '#FAF5FF',
    '--sidebar-ring': '#A855F7',
    '--color-primary-soft': '#FAF5FF',
  }),
  theme({
    id: 'copper',
    name: 'Copper',
    description: 'Earthy amber actions with slate content.',
    swatches: ['#B45309', '#0F766E', '#DC2626'],
  }, {
    '--primary': '#B45309',
    '--ring': '#B45309',
    '--secondary': '#FFFBEB',
    '--muted': '#FFFBEB',
    '--accent': '#FFFBEB',
    '--chart-1': '#B45309',
    '--chart-2': '#0F766E',
    '--sidebar-primary': '#B45309',
    '--sidebar-accent': '#FFFBEB',
    '--sidebar-ring': '#B45309',
    '--color-primary-soft': '#FFFBEB',
  }),
  theme({
    id: 'mono',
    name: 'Mono Slate',
    description: 'Minimal slate accents with restrained contrast.',
    swatches: ['#475569', '#64748B', '#94A3B8'],
  }, {
    '--primary': '#475569',
    '--ring': '#475569',
    '--secondary': '#F8FAFC',
    '--muted': '#F8FAFC',
    '--accent': '#F8FAFC',
    '--chart-1': '#475569',
    '--chart-2': '#64748B',
    '--chart-3': '#94A3B8',
    '--sidebar-primary': '#475569',
    '--sidebar-accent': '#F8FAFC',
    '--sidebar-ring': '#475569',
    '--color-primary-soft': '#F8FAFC',
  }),
];

export const personalizationThemeMap = new Map(
  personalizationThemes.map((themeOption) => [themeOption.id, themeOption])
);
